### ISSUE TITLE
Does this no longer work?

### ISSUE THREAD

**Issue by jesskrich** [LiberatedPixelCup/Universal-LPC-Spritesheet-Character-Generator#18]
Edit: never mind. Looks like there are no character sprites in the file anyway.

**Comment by jrconway3** [comment]
The way this worked originally is that it pulled all the character sprites from Makrohn's Universal-LPC-Spritesheet. When Sanderfrenken took over, however, both just got merged into one. And now Guarav has updated to Sanderfrenken's latest branch and shifted this to an organization instead, so this can safely be closed out. Its running on Sanderfrenken's fork now.
