### ISSUE TITLE
The gold helmet has no death animation

### ISSUE THREAD

**Issue by The-End-Is-Near** [LiberatedPixelCup/Universal-LPC-Spritesheet-Character-Generator#25]
Hello, I downloaded the files to make my own game, but the thing is that the gold helmet just does not have a death animation. Could you please fix it? Also could you email me at galacticquasar2000@gmail.com regarding the legal actions I need to take in order to legally use the spritesheet generator in my game? Thank you.

![golden_helm_male](https://user-images.githubusercontent.com/70327015/104454051-34438a00-559d-11eb-8f9b-47264c2dd242.png)
**No death animation**

**Comment by jrconway3** [comment]
Guarav transferred this repo to an org now, and well, this issue was resolved a while ago. So we can safely close this.
