### ISSUE TITLE
gaurav.munjal.us website no longer running

### ISSUE THREAD

**Issue by dynamicdicestudios** [LiberatedPixelCup/Universal-LPC-Spritesheet-Character-Generator#26]
I wanted to use the LPC Spritesheet Character Generator, but it says, "This site has stepped out for a bit" when I go to the link.

How long will the website be down? I really enjoyed it, so I hope the answer isn't indefinitely.

**Comment by Gaurav0** [comment]
Thanks for reporting, i was unaware that it was down. I haven't worked on this in a few years. It looks like it got some malware and is suspended for your safety. I may have to set it up all over again.

**Comment by josiahdetto** [comment]
No worries. Glad to hear that the site isn't gone forever :)

May I ask how long you think it might take to set it up again?

**Comment by FilipeCollura** [comment]
Are there plans to bring the site back up?

**Comment by Gaurav0** [comment]
It looks like an updated version of this site is being maintained by @sanderfranken here: https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/

I no longer plan to maintain the site.

**Comment by FilipeCollura** [comment]
Thank you for responding, glad this tool is still being maintained by other users.
